### PR TITLE
Rough draft for Winter 2019 LibreTexts team

### PR DESCRIPTION
**Pull request by lux12337**

### CODE REVIEW

**Comment by moorepants** [comment]
Please make a pull request from this repository to the primary repository. Don't merge into the source branch of the fork, that's not good practice.

**Comment by celine168** [comment]
When you say "Don't merge into the source branch of the fork," do you mean I shouldn't have merged Luigi's fork into the LibreTexts fork or don't merge this fork directly into your repository? If the former, should I have made another branch other than source on this fork?

**Comment by moorepants** [comment]
This looks like a good guide: https://gist.github.com/vlandham/3b2b79c40bc7353ae95a

The key is that you request that your branch on your fork be pulled into master of the main repo.

**Comment by moorepants** [comment]
Here's another: https://yangsu.github.io/pull-request-tutorial/

**Pull request merged**
